### ISSUE TITLE
Building the project

### ISSUE THREAD

**Issue by kakai248** [gilvegliach/TransparentTextTextView#2] opened 2016-03-20 15:55 UTC
Hello,

I'm having a hard time building this project. I can't seem to import it in Android Studio and be able to build it. Don't really know how to configure it. Any tips?

Even jitpack is not being able to do it (this is in my fork):
[See here](https://jitpack.io/com/github/kakai248/TransparentTextTextView/7c3672cde0/build.log)

Thanks

**Comment by gilvegliach** [comment] 2016-03-20 17:01
Thanks for the feedback. The problem is in the android-jcentre.gradle script, a small script that helps me upload the lib onto bintray and that I'll eventually release as a gradle plugin. 

Quick fix: uncomment line 55 in android-jcentre.gradle:

```
 //apply from: 'android-jcenter.gradle'
```

and build from the project root with:

```
./gradlew clean assembleRelease
```

I'll take a look to the PR tomorrow. Thanks again :+1:

**Comment by gilvegliach** [comment] 2016-03-25 20:09
Fixed on master. The line that applied the android-jcenter plug-in was moved up in a refactoring and was the cause of the bug.

**Closed as completed by gilvegliach** 2016-03-25 20:09 UTC

**Comment by gilvegliach** [comment] 2016-03-25 22:45
I release 1.0.2 which fixes the build and the other pr. I also put you in the change log :)

**Comment by kakai248** [comment] 2016-03-26 17:19
Just tested and it's working perfectly. Thanks mate!

**Comment by gilvegliach** [comment] 2016-03-26 20:42
No worries mate :)
